name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install essential packages
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          openjdk-17-jdk \
          zip \
          unzip \
          git \
          zlib1g-dev

    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install cython buildozer

    - name: Accept Android SDK licenses automatically
      run: |
        mkdir -p ~/.android
        echo "### LICENSE ACCEPTANCE ###" > ~/.android/licenses.properties
        echo "8933bad161af4178b1185d1a37fbf41ea5269c55" >> ~/.android/licenses.properties
        echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> ~/.android/licenses.properties
        echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" >> ~/.android/licenses.properties
        echo "84831b9409646a918e30573bab4c9c91346d8abd" >> ~/.android/licenses.properties
        cat ~/.android/licenses.properties

    - name: Build APK with retry
      run: |
        # Try building (this will accept any additional licenses)
        buildozer -v android debug || echo "First attempt completed"
        # Build again to ensure everything is accepted
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: baurik-app
        path: bin/*.apk
