name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git \
          zip \
          unzip \
          openjdk-17-jdk \
          python3-pip \
          autoconf \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses5-dev \
          libncursesw5-dev \
          libtinfo5 \
          cmake \
          libffi-dev \
          libssl-dev \
          build-essential \
          python3-venv

    - name: Install Buildozer and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython virtualenv

    - name: Set up Buildozer environment
      run: |
        buildozer init
        # Update buildozer.spec with correct settings
        sed -i 's/requirements = python3,kivy/requirements = python3,kivy/g' buildozer.spec
        sed -i 's/android.api = 30/android.api = 28/g' buildozer.spec
        sed -i 's/android.minapi = 21/android.minapi = 21/g' buildozer.spec
        sed -i 's/android.ndk = .*/#android.ndk = /g' buildozer.spec

    - name: Build APK (with timeout)
      run: |
        timeout 45m buildozer -v android debug || echo "Build completed or timed out"
        
    - name: Check for APK file
      run: |
        if ls bin/*.apk 1> /dev/null 2>&1; then
          echo "APK found successfully!"
          ls -la bin/
        else
          echo "No APK found, checking error logs..."
          find . -name "*.log" -exec echo "=== {} ===" \; -exec cat {} \;
          exit 1
        fi

    - name: Upload APK artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: baurik-cleaning-app
        path: bin/*.apk
