name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install essential packages
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          openjdk-17-jdk \
          zip \
          unzip \
          git \
          zlib1g-dev

    - name: Install Python build dependencies
      run: |
        pip install --upgrade pip
        pip install cython buildozer  # Added cython here!

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: baurik-app
        path: bin/*.apk
