name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04  # Changed from ubuntu-latest to 22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git \
          zip \
          unzip \
          openjdk-17-jdk \
          python3-pip \
          autoconf \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses5-dev \
          libncursesw5-dev \
          libtinfo5 \  # This package exists in Ubuntu 22.04
          cmake \
          libffi-dev \
          libssl-dev \
          build-essential \
          python3-venv

    - name: Install Buildozer and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython virtualenv

    - name: Set up Buildozer
      run: |
        buildozer init || echo "Buildozer already initialized"
        # Ensure correct configuration
        [ -f buildozer.spec ] || exit 1

    - name: Build APK (with timeout)
      run: |
        timeout 45m buildozer -v android debug || echo "Build completed or timed out"
        
    - name: Check for APK file
      run: |
        if ls bin/*.apk 1> /dev/null 2>&1; then
          echo "APK found successfully!"
          ls -la bin/
        else
          echo "No APK found, checking error logs..."
          find . -name "*.log" -exec echo "=== {} ===" \; -exec head -50 {} \;
          exit 1
        fi

    - name: Upload APK artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: baurik-cleaning-app
        path: bin/*.apk
