name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install essential packages
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          openjdk-17-jdk \
          zip \
          unzip \
          git \
          zlib1g-dev

    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install cython buildozer

    - name: Configure Android SDK to use newer build-tools
      run: |
        # Initialize buildozer
        buildozer init || true
        
        # Force newer Android build-tools version
        sed -i 's/#android.build_tools_version = /android.build_tools_version = 34.0.0/' buildozer.spec
        sed -i 's/android.api = 28/android.api = 33/' buildozer.spec
        sed -i 's/android.minapi = 21/android.minapi = 21/' buildozer.spec
        
        # Show the updated config
        grep -E "(android.api|android.minapi|android.build_tools_version)" buildozer.spec

    - name: Accept all Android licenses automatically
      run: |
        mkdir -p ~/.android
        # Pre-accept all common licenses
        yes | ${ANDROID_HOME}/tools/bin/sdkmanager --licenses 2>/dev/null || true
        echo "Licenses pre-accepted"

    - name: Build APK with retry
      run: |
        # Build with auto-accept for any remaining licenses
        yes | buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: baurik-app
        path: bin/*.apk

    - name: Show build results
      run: ls -la bin/ || echo "Build directory contents:"
