name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 60  # Increased timeout

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip openjdk-17-jdk
        pip install cython buildozer

    - name: Configure buildozer with modern settings
      run: |
        # Create a fresh buildozer.spec
        cat > buildozer.spec << 'EOL'
[app]
title = Baurik Cleaning Solutions
package.name = baurikcleaning
package.domain = com.baurik
version = 1.0
source.dir = .
source.main = main.py
requirements = python3,kivy
orientation = portrait
android.permissions = INTERNET
android.api = 33
android.minapi = 21
android.build_tools_version = 34.0.0
log_level = 2
EOL

    - name: Build APK with detailed logging
      run: |
        # Set longer timeout and better error handling
        timeout 50m buildozer -v android debug 2>&1 | tee build.log || {
          echo "Build completed or timed out"
          # Check if APK was created despite exit code
          if [ -f bin/*.apk ]; then
            echo "APK was created successfully!"
            exit 0
          fi
          echo "Build failed. Showing last 50 lines of log:"
          tail -50 build.log
          exit 1
        }

    - name: Check for APK file
      run: |
        echo "Checking for APK files..."
        if ls bin/*.apk 1> /dev/null 2>&1; then
          echo "✅ APK found:"
          ls -la bin/
          echo "APK_BUILT=true" >> $GITHUB_ENV
        else
          echo "❌ No APK found. Build log:"
          tail -100 build.log | grep -A 20 -B 20 "error\|Error\|ERROR\|failed\|Failed"
          echo "APK_BUILT=false" >> $GITHUB_ENV
        fi

    - name: Upload APK if exists
      if: env.APK_BUILT == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: baurik-app
        path: bin/*.apk

    - name: Upload build log for debugging
      if: env.APK_BUILT == 'false'
      uses: actions/upload-artifact@v4
      with:
        name: build-log
        path: build.log
