name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup environment
      run: |
        sudo apt update
        sudo apt install -y python3-pip openjdk-17-jdk
        pip install cython buildozer

    - name: Create minimal buildozer.spec
      run: |
        echo '[app]
title = Baurik Cleaning Solutions
package.name = baurikcleaning
package.domain = com.baurik
version = 1.0
source.dir = .
source.main = main.py
requirements = python3,kivy
orientation = portrait
android.permissions = INTERNET
android.api = 33
android.minapi = 21' > buildozer.spec

    - name: Build with debug logging
      run: |
        # Build with explicit yes and save log
        buildozer -v android debug > build.log 2>&1 || true
        
        # Check if APK was created despite exit code
        if ls bin/*.apk 1> /dev/null 2>&1; then
          echo "✅ APK built successfully!"
          exit 0
        else
          echo "❌ Build failed. Last errors:"
          tail -30 build.log
          exit 1
        fi

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: baurik-app
        path: bin/*.apk
